import OpenAI from "openai";
import dotenv from 'dotenv';
//import fs from 'fs';

dotenv.config();

class openaichat{
    constructor(apiKey) {
        this.openai = new OpenAI({ apiKey: process.env.openaikey})
    }
    
    async getChatCompletion(chat, userThreadID) { //call this function within the created object with the user's message and their thread_id (use: "thread_DlQO7yZt4PvJOmMbz8D5zLhj" for testing)
        this.assistant = await this.openai.beta.assistants.retrieve("asst_vhKUyzAvbJVVETPj1J5tVoai");
        this.thread = await this.openai.beta.threads.retrieve(userThreadID);
        this.message = await this.openai.beta.threads.messages.create(
            this.thread.id,
            {
                role: "user",
                content: chat 
            }
        );
       
        let run = await this.openai.beta.threads.runs.createAndPoll(
            this.thread.id,
            {
                assistant_id: this.assistant.id
            }
        );
        if (run.status === 'completed') {
            this.messages = await this.openai.beta.threads.messages.list(
              run.thread_id,{order: 'desc',limit: 1}
            );
            this.lastmsg = await this.openai.beta.threads.messages.retrieve(this.thread.id,this.messages.data[0].id);
            this.textvalue = this.lastmsg.content[0].text.value

            //this bit is to extract and create the json file
            const jsonMatch = this.textvalue.match(/```json([\s\S]*?)```/); //used this to extract json that was generated by the assistant
            if (jsonMatch && jsonMatch[1]) {
                const jsonData = JSON.parse(jsonMatch[1].trim()); //to remove whitespace :)              
                
                //fs.writeFileSync('diagnosis.json', JSON.stringify(jsonData, null, 2)); //to write diagnosis.json
                
                return jsonData;

            } else {

                return this.textvalue;

            }
            
            //console.log(textvalue); 
            
            //from API Reference page (only used for testing)
            //for (const message of messages.data.reverse()) {
             // console.log(`${message.role} > ${message.content[0].text.value}`);
            //}
          //} else {
           // console.log(run.status);
        }
    
    }
}


export default openaichat;

