import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, ScrollView, CheckBox } from 'react-native';
import { useNavigation } from '@react-navigation/native';

const ProfileScreen = () => {
  const navigation = useNavigation();
  const [isTermsVisible, setIsTermsVisible] = useState(false);
  const [isAgreed, setIsAgreed] = useState(false);

  const handleTermsPress = () => {
    setIsTermsVisible(true);
  };

  const handleCloseTermsModal = () => {
    setIsTermsVisible(false);
  };

  return (
    <View style={styles.container}>
      <View style={styles.profileHeader}>
        <View style={styles.profilePic} />
        <Text style={styles.profileName}>Jane Doe</Text>
        <Text style={styles.profileEmail}>janedoe@gmail.com</Text>
        <TouchableOpacity
          style={styles.editProfileButton}
          onPress={() => navigation.navigate('editprofile')}
        >
          <Text style={styles.editProfileText}>Edit Profile</Text>
        </TouchableOpacity>
      </View>
      <View style={styles.menu}>
        <TouchableOpacity style={styles.menuItem}>
          <Text style={styles.menuText}>Account Details</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.menuItem}>
          <Text style={styles.menuText}>Medical Record</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.menuItem} onPress={handleTermsPress}>
          <Text style={styles.menuText}>Terms & Conditions</Text>
        </TouchableOpacity>
      </View>
      <View style={styles.footer}>
        <TouchableOpacity>
          <Text style={styles.logoutText}>Log out</Text>
        </TouchableOpacity>
        <TouchableOpacity>
          <Text style={styles.deleteAccountText}>Delete my account</Text>
        </TouchableOpacity>
        <Text style={styles.footerText}>Developed by GMC.</Text>
      </View>

      {/* Terms and Conditions Modal */}
      <Modal
        transparent={true}
        visible={isTermsVisible}
        animationType="slide"
        onRequestClose={handleCloseTermsModal}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <Text style={styles.modalHeader}>Terms and Conditions</Text>
            <ScrollView style={styles.modalScrollView}>
              <Text style={styles.modalText}>
                **Effective Date:** [Insert Date]
                {'\n\n'}
                Welcome to MedAlly! By using our application, you agree to the following terms and conditions. Please read them carefully.
                {'\n\n'}
                **1. General Use**
                {'\n'}
                1.1 MedAlly is designed to provide health and medicine-related information to enhance user accessibility to healthcare tools. However, it is not a substitute for professional medical advice, diagnosis, or treatment.
                {'\n'}
                1.2 The information provided by MedAlly should not be taken as professional medical advice. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                {'\n\n'}
                **2. AI Technology and Limitations**
                {'\n'}
                2.1 MedAlly incorporates AI technologies, including but not limited to symptom-based health diagnosis, health advice, medication recommendations, meal logging, nutritional analysis, medication management, and safety alerts.
                {'\n'}
                2.2 While we strive to provide accurate and up-to-date information, AI technology is not perfect and may be subject to errors. The results and recommendations generated by the AI should be used as a general guide and not as definitive medical advice.
                {'\n'}
                2.3 Users acknowledge that the AI's recommendations are based on the information provided by the user and existing medical records. Inaccurate or incomplete information may affect the AI's output.
                {/* Continue the rest of the terms and conditions text */}
              </Text>
            </ScrollView>
            <View style={styles.checkboxContainer}>
              <CheckBox
                value={isAgreed}
                onValueChange={setIsAgreed}
              />
              <Text style={styles.checkboxLabel}>I agree to the Terms and Conditions</Text>
            </View>
            <TouchableOpacity
              style={[styles.closeButton, { backgroundColor: isAgreed ? '#007BFF' : '#cccccc' }]}
              disabled={!isAgreed}
              onPress={handleCloseTermsModal}
            >
              <Text style={styles.closeButtonText}>Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    padding: 20,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 20,
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 3,
  },
  profilePic: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#ccc',
    marginBottom: 10,
  },
  profileName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  profileEmail: {
    fontSize: 14,
    color: '#777',
    marginBottom: 15,
  },
  editProfileButton: {
    backgroundColor: '#000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  editProfileText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  menu: {
    marginBottom: 20,
  },
  menuItem: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 10,
  },
  menuText: {
    fontSize: 16,
  },
  footer: {
    alignItems: 'center',
  },
  logoutText: {
    fontSize: 16,
    color: '#000',
    marginBottom: 10,
  },
  deleteAccountText: {
    fontSize: 16,
    color: '#ff0000',
    marginBottom: 20,
  },
  footerText: {
    fontSize: 12,
    color: '#777',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalScrollView: {
    maxHeight: 300,
    marginBottom: 20,
  },
  modalText: {
    fontSize: 14,
    lineHeight: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  checkboxLabel: {
    fontSize: 14,
    marginLeft: 10,
  },
  closeButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
});

export default ProfileScreen;
